<?php
/**
 * @file
 * Contains the theme implementations provided by fortyfour.
 */

/**
 * Implementation of HOOK_theme().
 */
/* -- Delete this line if you want to use this function
function _fortyfour_theme(&$existing, $type, $theme, $path) {
  $theme_hooks = array(
    'sameple_theme_function' => array(
      'variables' => array('url' => NULL, 'title' => NULL, 'description' => NULL, 'subtext' => NULL, 'link_text' => NULL),
    ),
  );

  return $theme_hooks;
}
// */

/* -- Delete this line if you want to use this function
function fortyfour_sample_theme_function(&$variables) {
  $variables['url'];
  $variables['title'];
}
// */
